#!/bin/bash




# crea un CA amb una clau de $bits bits, el valor que se li passa
# el ftixer de claus no té password
# creac el certificat autosignat amb una durada de 5 anys
# la clau es guarda al fitxer cakey.pem
# el certificat autosignat es guarda en el fitxer certificatcaroot.crt

bits=$1

# generem dades aleatories per a la clau

openssl rand -out rand.txt 2000

# crea una clau rsa amb l'openssl

openssl genrsa -out cakey.pem $bits -rand rand.txt

rm rand.txt

# mostra la clau per pantalla
openssl rsa -in cakey.pem -text -noout

# crea el cetificat autosignat

openssl req -new -x509 -sha1 -days 1826 -key cakey.pem -out certificatcaroot.crt 

# mostra el certificat per pantalla

openssl x509 -in certificatcaroot.crt -noout -text
